/*
 * Aggregate support functions (transition/combine/final/serial) are pure
 * computations over their arguments; without an explicit marking they
 * default to PARALLEL UNSAFE, which forbids partial parallel aggregation
 * for every $group. Mark them PARALLEL SAFE on existing installs.
 */
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_sum_avg_transition(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_sum_avg_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_sum_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_avg_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_min_max_final(__CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_max_transition(__CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_min_transition(__CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_min_combine(__CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_max_combine(__CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_first_transition(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson[]) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_last_transition(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson[]) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_first_transition_on_sorted(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_last_transition_on_sorted(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_first_last_final_on_sorted(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_first_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_last_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_first_last_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_array_agg_transition(bytea, __CORE_SCHEMA__.bson, text) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_array_agg_transition(bytea, __CORE_SCHEMA__.bson, text, boolean) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_array_agg_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_object_agg_transition(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_object_agg_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_firstn_transition(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson[]) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_lastn_transition(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson[]) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_firstn_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_lastn_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_firstn_lastn_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_firstn_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_lastn_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_firstn_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, bigint) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_lastn_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, bigint) PARALLEL SAFE;
ALTER FUNCTION __API_CATALOG_SCHEMA__.bson_firstn_lastn_final_on_sorted(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_add_to_set_transition(bytea, __CORE_SCHEMA_V2__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_add_to_set_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_merge_objects_transition_on_sorted(bytea, __CORE_SCHEMA_V2__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_merge_objects_transition(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson[], __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_merge_objects_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_std_dev_pop_samp_transition(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_std_dev_pop_samp_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_std_dev_pop_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_std_dev_samp_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_first_transition(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson[], __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_last_transition(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson[], __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_firstn_transition(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson[], __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_lastn_transition(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson[], __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_maxn_transition(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_minn_transition(bytea, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_maxminn_final(bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_maxminn_combine(bytea, bytea) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_first_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_last_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_firstn_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_lastn_transition_on_sorted(bytea, __CORE_SCHEMA__.bson, bigint, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_add_double(internal, __CORE_SCHEMA__.bson, int4, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_add_double_array(internal, __CORE_SCHEMA__.bson, int4, __CORE_SCHEMA__.bson) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_percentile(internal) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_array_percentiles(internal) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_combine(internal, internal) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_serial(internal) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.tdigest_deserial(bytea, internal) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_count_transition(int8, int4) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_count_combine(int8, int8) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_count_final(int8) PARALLEL SAFE;
ALTER FUNCTION __API_SCHEMA_INTERNAL_V2__.bson_command_count_final(int8) PARALLEL SAFE;
